name: Check Markdown links

# Schechule makes more sense
on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 #clones
    - uses: gaurav-nelson/github-action-markdown-link-check@v1 
      with:
        use-verbose-mode: 'yes'
        folder-path: 'docs/markdown_files' 
        max-depth: 2
